project_id = "gwphpsehcnhwjiypyolg"

[functions.eupago-webhook]
verify_jwt = false

[functions.sync-egoi]
verify_jwt = false

[functions.get-leaderboard]
verify_jwt = false

[functions.generate-reminder]
verify_jwt = false

[functions.followup-abandoned]
verify_jwt = false

[functions.invoice-upsert]
verify_jwt = false

[functions.resolve-payment]
verify_jwt = false