import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,Legend} from 'recharts';
import {courseInsights} from '@/lib/course/insights';
import type {Inscrito} from '@/pages/crm/mockData';
export default function CourseInsights({items,period,onSelect}:{items:Inscrito[];period:string;onSelect:(i:Inscrito)=>void}) {
 const {sources,dates,priorities}=courseInsights(items,period);
 return <div className="space-y-5 my-5">
 <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Próximas ações</h2><p className="text-sm text-slate-500 mb-3">Contactos vencidos e pagamentos ou faturas em verificação. Exclui contactos pausados e inscrições canceladas.</p>{priorities.length?<ul className="divide-y">{priorities.slice(0,10).map(i=><li key={i.id}><button className="py-3 w-full flex flex-wrap gap-2 justify-between text-left text-sm hover:text-blue-700" onClick={()=>onSelect(i)}><strong>{i.nome} · {i.course?.editionLabel}</strong><span>{i.course?.paymentState==='review'?'Verificar pagamento':i.course?.invoiceState==='review'?'Verificar fatura':'Contacto em atraso'}</span></button></li>)}</ul>:<p className="text-sm">Sem ações em atraso nesta seleção.</p>}{priorities.length>10 && <p className="text-xs text-slate-500">Mostradas 10 de {priorities.length}; consulte a tabela para a lista completa.</p>}</section>
 <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Inscrições por dia · hora de Lisboa</h2><p className="text-sm text-slate-500 mb-4">Inscrições criadas no período e quantas já têm pagamento confirmado. Dias sem inscrições não aparecem.</p>{dates.length?<div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={dates}><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis allowDecimals={false}/><Tooltip/><Legend/><Bar dataKey="requests" name="Pedidos" fill="#2563eb" isAnimationActive={false}/><Bar dataKey="paid" name="Pagos desta coorte" fill="#16a34a" isAnimationActive={false}/></BarChart></ResponsiveContainer></div>:<p className="text-sm">Sem inscrições neste período.</p>}</section>
 <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold mb-2">Origem das inscrições</h2><p className="text-sm text-slate-500 mb-4">Atribuição guardada no pedido. Conversão desta coorte: pagos ÷ pedidos. Não estima visitas sem consentimento.</p><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Origem','Pedidos','Pagos','Conversão','Recebido c/ IVA'].map(x=><th key={x} className="text-left p-2 border-b">{x}</th>)}</tr></thead><tbody>{sources.map(x=><tr key={x.source}><td className="p-2 break-all">{x.source}</td><td className="p-2">{x.requests}</td><td className="p-2">{x.paid}</td><td className="p-2">{(100*x.paid/x.requests).toFixed(1)}%</td><td className="p-2">{x.revenue.toLocaleString('pt-PT',{style:'currency',currency:'EUR'})}</td></tr>)}</tbody></table>{!sources.length && <p className="text-sm py-3">Sem atribuição para analisar neste período.</p>}</div></section>
 </div>;
}
