
INSERT INTO public.email_templates (template_key, name, subject, html_body, text_body, variables, is_active, version, channel, updated_by)
VALUES
(
  'video_masterclass_thankyou',
  'Pós-Masterclass — Obrigado',
  'Obrigado, {{fname}} — foi um prazer ter-te na Masterclass',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Georgia,serif"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;padding:32px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06)"><tr><td style="background:linear-gradient(135deg,#16a34a,#15803d);padding:32px 40px;text-align:center"><h1 style="margin:0;font-size:22px;color:#ffffff;font-weight:700;font-family:Georgia,serif">Obrigado, {{fname}} 🎬</h1><p style="margin:8px 0 0;font-size:14px;color:rgba(255,255,255,0.85);font-family:Georgia,serif">Foi um prazer ter-te na Masterclass</p></td></tr><tr><td style="padding:32px 40px"><p style="font-size:15px;line-height:1.7;color:#1a1a1a;margin:0 0 16px">Olá {{fname}},</p><p style="font-size:15px;line-height:1.7;color:#1a1a1a;margin:0 0 16px">A Masterclass terminou há pouco e ainda estou a processar a energia que a sala teve hoje.</p><p style="font-size:15px;line-height:1.7;color:#1a1a1a;margin:0 0 16px">Foram três horas intensas. Saíste com um sistema que podes começar a usar amanhã — agentes de IA, fluxos de montagem, edição em linguagem natural. Não teoria. Processo.</p><p style="font-size:15px;line-height:1.7;color:#1a1a1a;margin:0 0 24px">O acesso aos recursos está disponível agora:</p><table cellpadding="0" cellspacing="0" style="margin:0 auto 24px"><tr><td style="background-color:#16a34a;border-radius:8px;padding:14px 28px;text-align:center"><a href="https://imagenscomia.com/recursos-video" style="color:#ffffff;font-size:15px;font-weight:700;text-decoration:none;font-family:Georgia,serif">Aceder aos meus recursos →</a></td></tr></table><p style="font-size:15px;line-height:1.7;color:#1a1a1a;margin:0 0 16px">Lá encontras a gravação da sessão de 5 de Março, o workbook, o guia dos GEMs e, assim que estiver disponível (nas próximas 24h), a gravação da Masterclass de hoje.</p><p style="font-size:15px;line-height:1.7;color:#1a1a1a;margin:0 0 24px">Se tiveres alguma questão técnica ou precisares de ajuda com algum passo, responde directamente a este email.</p><p style="font-size:15px;line-height:1.7;color:#1a1a1a;margin:0 0 4px">Até breve,</p><p style="font-size:15px;line-height:1.7;color:#1a1a1a;margin:0;font-weight:700">Frederico Carvalho</p><p style="font-size:13px;color:#666;margin:4px 0 0">DIGITALFC · fredericocarvalho.pt</p></td></tr></table></td></tr></table></body></html>',
  E'Olá {{fname}},\n\nA Masterclass terminou há pouco e ainda estou a processar a energia que a sala teve hoje.\n\nForam três horas intensas. Saíste com um sistema que podes começar a usar amanhã — agentes de IA, fluxos de montagem, edição em linguagem natural. Não teoria. Processo.\n\nO acesso aos recursos está disponível agora:\n→ Aceder aos meus recursos: https://imagenscomia.com/recursos-video\n\nLá encontras a gravação da sessão de 5 de Março, o workbook, o guia dos GEMs e, assim que estiver disponível (nas próximas 24h), a gravação da Masterclass de hoje.\n\nSe tiveres alguma questão técnica ou precisares de ajuda com algum passo, responde directamente a este email.\n\nAté breve,\nFrederico Carvalho\nDIGITALFC · fredericocarvalho.pt',
  '["fname"]'::jsonb,
  true,
  1,
  'email',
  'crm'
),
(
  'video_masterclass_day1',
  'Masterclass Day 1 — Recursos + Avaliação',
  '{{fname}}, a gravação já está disponível',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#f4f4f4;font-family:Georgia,serif"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4;padding:32px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06)"><tr><td style="background:linear-gradient(135deg,#16a34a,#15803d);padding:32px 40px;text-align:center"><h1 style="margin:0;font-size:22px;color:#ffffff;font-weight:700;font-family:Georgia,serif">{{fname}}, a gravação está pronta 🎬</h1></td></tr><tr><td style="padding:32px 40px"><p style="font-size:15px;line-height:1.7;color:#1a1a1a;margin:0 0 16px">Olá {{fname}},</p><p style="font-size:15px;line-height:1.7;color:#1a1a1a;margin:0 0 16px">A gravação da Masterclass de ontem já está disponível na tua área de recursos.</p><table cellpadding="0" cellspacing="0" style="margin:0 auto 24px"><tr><td style="background-color:#16a34a;border-radius:8px;padding:14px 28px;text-align:center"><a href="https://imagenscomia.com/recursos-video" style="color:#ffffff;font-size:15px;font-weight:700;text-decoration:none;font-family:Georgia,serif">Ver a gravação →</a></td></tr></table><p style="font-size:15px;line-height:1.7;color:#1a1a1a;margin:0 0 16px">Uma coisa que aprendi ao longo dos anos: a primeira vez que assistes a uma sessão ao vivo absorves o fluxo. A segunda vez — na gravação, ao teu ritmo — é quando percebes os detalhes que escaparam.</p><p style="font-size:15px;line-height:1.7;color:#1a1a1a;margin:0 0 24px">Vale a pena rever.</p><hr style="border:none;border-top:1px solid #e5e5e5;margin:24px 0"><p style="font-size:15px;line-height:1.7;color:#1a1a1a;margin:0 0 16px"><strong>Um pedido, se fizer sentido:</strong></p><p style="font-size:15px;line-height:1.7;color:#1a1a1a;margin:0 0 16px">Se a sessão foi útil para o teu trabalho, uma avaliação no Google ajuda outras pessoas a encontrar este conteúdo — e ajuda-me a continuar a produzi-lo.</p><table cellpadding="0" cellspacing="0" style="margin:0 auto 24px"><tr><td style="background-color:#ffffff;border:2px solid #16a34a;border-radius:8px;padding:12px 24px;text-align:center"><a href="https://g.page/r/CQnSiNwBJsJoEBM/review" style="color:#16a34a;font-size:14px;font-weight:700;text-decoration:none;font-family:Georgia,serif">⭐ Deixar avaliação no Google (2 min)</a></td></tr></table><p style="font-size:15px;line-height:1.7;color:#1a1a1a;margin:0 0 16px">Não é obrigatório. Mas se o fizeres, agradeço.</p><p style="font-size:15px;line-height:1.7;color:#1a1a1a;margin:0 0 4px;font-weight:700">Frederico Carvalho</p><p style="font-size:13px;color:#666;margin:4px 0 0">DIGITALFC · fredericocarvalho.pt</p></td></tr></table></td></tr></table></body></html>',
  E'Olá {{fname}},\n\nA gravação da Masterclass de ontem já está disponível na tua área de recursos.\n\n→ Ver a gravação: https://imagenscomia.com/recursos-video\n\nUma coisa que aprendi ao longo dos anos: a primeira vez que assistes a uma sessão ao vivo absorves o fluxo. A segunda vez — na gravação, ao teu ritmo — é quando percebes os detalhes que escaparam.\n\nVale a pena rever.\n\n---\n\nUm pedido, se fizer sentido:\n\nSe a sessão foi útil para o teu trabalho, uma avaliação no Google ajuda outras pessoas a encontrar este conteúdo — e ajuda-me a continuar a produzi-lo.\n\n→ Deixar avaliação no Google (2 minutos): https://g.page/r/CQnSiNwBJsJoEBM/review\n\nNão é obrigatório. Mas se o fizeres, agradeço.\n\nFrederico Carvalho\nDIGITALFC · fredericocarvalho.pt',
  '["fname"]'::jsonb,
  true,
  1,
  'email',
  'crm'
)
ON CONFLICT (template_key) DO NOTHING;
