
ALTER TABLE public.registrations
  ADD COLUMN IF NOT EXISTS premium_granted_at TIMESTAMPTZ DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS premium_granted_by TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS is_gift BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS gift_code TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS gifted_at TIMESTAMPTZ DEFAULT NULL;
